import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ShieldCheck, Users, Activity, LogOut, Bell, CircleHelp, Send, Image as ImageIcon, LayoutDashboard } from 'lucide-react';
import { fetchAdminStatsApi, fetchFarmersApi, fetchHelpRequestsApi, fetchAlertsApi, logout, sendAdminAlertApi, updateHelpRequestApi } from '../services/api';

export default function AdminDashboard(){
 const navigate=useNavigate(); const [stats,setStats]=useState<any>(); const [farmers,setFarmers]=useState<any[]>([]); const [helps,setHelps]=useState<any[]>([]); const [alerts,setAlerts]=useState<any[]>([]); const [tab,setTab]=useState('overview'); const [title,setTitle]=useState(''); const [message,setMessage]=useState(''); const [target,setTarget]=useState('all'); const [image,setImage]=useState<File>(); const [reply,setReply]=useState<Record<number,string>>({}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{try{const [s,f,h,a]=await Promise.all([fetchAdminStatsApi(),fetchFarmersApi(),fetchHelpRequestsApi(),fetchAlertsApi()]);setStats(s);setFarmers(f);setHelps(h);setAlerts(a)}catch(e:any){setError(e.message)}}; useEffect(()=>{load()},[]);
 const send=async()=>{if(!title.trim()||!message.trim())return setError('Alert title and message are required.');setBusy(true);try{await sendAdminAlertApi(title,message,target,image);setTitle('');setMessage('');setImage(undefined);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const update=async(id:number,status:string)=>{try{await updateHelpRequestApi(id,status,reply[id]||'');await load()}catch(e:any){setError(e.message)}};
 return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900 sticky top-0 z-30"><div className="max-w-7xl mx-auto px-5 py-4 flex justify-between items-center"><div className="flex gap-3 items-center"><div className="h-11 w-11 rounded-xl bg-emerald-600 flex items-center justify-center"><ShieldCheck/></div><div><h1 className="font-black text-lg">AgriNivara Admin</h1><p className="text-xs text-slate-400">Farmer support & AI agriculture operations</p></div></div><button onClick={()=>{logout();navigate('/login',{replace:true})}} className="px-4 py-2 rounded-xl bg-slate-800 flex gap-2 items-center"><LogOut size={16}/>Logout</button></div></header>
 <main className="max-w-7xl mx-auto p-5 lg:p-8"><div className="mb-7"><p className="text-emerald-400 text-xs font-bold tracking-widest">ADMIN CONTROL CENTER</p><h2 className="text-3xl font-black mt-2">AgriNivara Operations Dashboard</h2><p className="text-slate-400 mt-2">Monitor farmers, resolve support requests and broadcast verified farm alerts.</p></div>{error&&<div className="mb-5 bg-red-950 border border-red-800 p-3 rounded-xl text-red-300">{error}</div>}
 <div className="grid md:grid-cols-4 gap-4"><Stat icon={<Users/>} t="Registered Farmers" v={stats?.total_users??'—'}/><Stat icon={<Activity/>} t="Successful Logins" v={stats?.total_logins??'—'}/><Stat icon={<CircleHelp/>} t="Open Help Requests" v={helps.filter(x=>x.status!=='Resolved').length}/><Stat icon={<Bell/>} t="Alerts Sent" v={alerts.length}/></div>
 <div className="mt-7 flex flex-wrap gap-2">{[['overview','Overview'],['farmers','Farmers'],['help','Help Requests'],['alerts','Send Alert']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2.5 rounded-xl text-sm font-bold ${tab===id?'bg-emerald-600':'bg-slate-900 border border-slate-800 text-slate-300'}`}>{label}</button>)}<Link to="/admin/farmer-view" className="ml-auto px-4 py-2.5 rounded-xl bg-white text-slate-900 text-sm font-bold flex gap-2 items-center"><LayoutDashboard size={16}/>Open Farmer Dashboard</Link></div>
 {tab==='overview'&&<div className="grid lg:grid-cols-2 gap-5 mt-5"><Panel title="Core AI Modules"><p>✓ Random Forest crop recommendation</p><p>✓ Explainable agronomic suitability analysis</p><p>✓ Live weather-aware decisions</p><p>✓ Plant disease image classification</p><p>✓ Yield planning & what-if analysis</p><p>✓ Farmer support + admin alert channel</p></Panel><Panel title="Demo Flow"><p className="text-slate-300">1. Register/login as farmer.</p><p className="text-slate-300">2. Search farm location and fetch live weather.</p><p className="text-slate-300">3. Run crop recommendation.</p><p className="text-slate-300">4. Upload disease image.</p><p className="text-slate-300">5. Send a help request.</p><p className="text-slate-300">6. Return here and resolve/send an alert.</p></Panel></div>}
 {tab==='farmers'&&<Panel title="Registered Farmers"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-slate-500"><tr><th className="text-left p-3">Name</th><th className="text-left p-3">Mobile</th><th className="text-left p-3">Location</th><th className="text-left p-3">Joined</th></tr></thead><tbody>{farmers.map(f=><tr key={f.id} className="border-t border-slate-800"><td className="p-3 font-bold">{f.name}</td><td className="p-3">{f.mobile}</td><td className="p-3">{f.location||'—'}</td><td className="p-3 text-slate-400">{new Date(f.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></Panel>}
 {tab==='help'&&<div className="mt-5 space-y-4">{helps.length===0?<Panel title="Help Requests"><p>No farmer requests yet.</p></Panel>:helps.map(h=><div key={h.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex justify-between gap-4"><div><p className="text-xs text-emerald-400 font-bold">REQUEST #{h.id}</p><h3 className="font-black mt-1">{h.name} · {h.mobile}</h3><p className="text-slate-400 text-xs">{new Date(h.created_at).toLocaleString()}</p></div><span className="px-3 py-1 rounded-full bg-slate-800 text-xs font-bold">{h.status}</span></div><p className="mt-4 text-slate-200">{h.message||'Image-only request'}</p>{h.image_data&&<img src={h.image_data} className="mt-3 max-h-56 rounded-xl"/>}<textarea value={reply[h.id]??h.admin_reply??''} onChange={e=>setReply({...reply,[h.id]:e.target.value})} placeholder="Admin reply (optional)" className="mt-4 w-full bg-slate-950 border border-slate-700 rounded-xl p-3"/><div className="mt-3 flex gap-2"><button onClick={()=>update(h.id,'In Progress')} className="px-3 py-2 rounded-lg bg-amber-600 text-sm font-bold">In Progress</button><button onClick={()=>update(h.id,'Resolved')} className="px-3 py-2 rounded-lg bg-emerald-600 text-sm font-bold">Resolve</button></div></div>)}</div>}
 {tab==='alerts'&&<div className="mt-5 grid lg:grid-cols-2 gap-5"><Panel title="Broadcast Farmer Alert"><label className="block text-sm font-bold">Title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full bg-slate-950 border border-slate-700 rounded-xl p-3" placeholder="Heavy rain advisory"/></label><label className="block text-sm font-bold mt-4">Message<textarea value={message} onChange={e=>setMessage(e.target.value)} className="mt-2 w-full bg-slate-950 border border-slate-700 rounded-xl p-3 h-32" placeholder="Tell farmers what action to take..."/></label><label className="block text-sm font-bold mt-4">Send to<select value={target} onChange={e=>setTarget(e.target.value)} className="mt-2 w-full bg-slate-950 border border-slate-700 rounded-xl p-3"><option value="all">All Farmers</option>{farmers.map(f=><option key={f.id} value={String(f.id)}>{f.name} ({f.mobile})</option>)}</select></label><label className="mt-4 flex items-center gap-2 text-sm font-bold"><ImageIcon size={17}/>Attach image<input type="file" accept="image/*" className="hidden" onChange={e=>setImage(e.target.files?.[0])}/></label>{image&&<p className="text-xs text-emerald-400 mt-2">{image.name}</p>}<button disabled={busy} onClick={send} className="mt-5 bg-emerald-600 px-5 py-3 rounded-xl font-black flex gap-2 items-center"><Send size={17}/>{busy?'Sending...':'Send Alert'}</button></Panel><Panel title="Recent Alerts">{alerts.slice(0,8).map(a=><div key={a.id} className="border-b border-slate-800 py-3"><b>{a.title}</b><p className="text-sm text-slate-400">{a.message}</p></div>)}</Panel></div>}
 </main></div>
}
function Stat({icon,t,v}:{icon:any,t:string,v:any}){return <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="text-emerald-400">{icon}</div><p className="text-xs text-slate-400 mt-4">{t}</p><b className="text-3xl mt-1 block">{v}</b></div>}
function Panel({title,children}:{title:string,children:any}){return <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><h3 className="text-lg font-black mb-4">{title}</h3><div className="space-y-3 text-sm text-slate-400">{children}</div></div>}
